# Generated by Django 4.1.1 on 2023-11-30 11:37

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_seccond_description_services_homepage_second_description_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='first_image_services',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.get_services_first_image_filepath),
        ),
        migrations.AddField(
            model_name='homepage',
            name='second_image_services',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.get_services_second_image_filepath),
        ),
        migrations.AddField(
            model_name='homepage',
            name='third_image_services',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.get_services_third_image_filepath),
        ),
    ]
