# Generated by Django 4.1.1 on 2023-11-22 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caregory',
            new_name='Category',
        ),
    ]
