# Generated by Django 4.1.1 on 2023-11-22 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_caregory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_at',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
