# Generated by Django 4.1.1 on 2023-11-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_orderitem_order_at_orderitem_order_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_time',
            new_name='order_at',
        ),
    ]
